Web/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web.Areas.Admin.Identity.ViewModels;
using Web.Controllers;
using Web.Extensions;
using Web.Identity;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {

        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<AppRole> _roleManager;

        public RoleController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> RoleList()
        {
            var roles = await _roleManager.Roles.Select(x => new RoleListViewModel
            {
                Id = x.Id,
                Name = x.Name!
            }).ToListAsync();

            return View(roles);
        }


        public IActionResult CreateRole()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel request)
        {
            var result = await _roleManager.CreateAsync(new AppRole
            {
                Name = request.Name
            });

            if (!result.Succeeded)
            {
                ModelState.AddModelErrorList(result.Errors);
                return View();
            }

            TempData["RoleAdded"] = true;
            return View();
        }


        public async Task<IActionResult> UpdateRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ModelState.AddModelError(string.Empty, "Böyle bir rol bulunamadı.");
                return View();
            }

            return View(new UpdateRoleViewModel
            {
                Id = role.Id,
                Name = role!.Name!
            });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateRole(UpdateRoleViewModel request)
        {
            var role = await _roleManager.FindByIdAsync(request.Id);

            if (role == null)
            {
                ModelState.AddModelError(string.Empty, "Böyle bir rol bulunamadı.");
                return View();
            }

            role.Name = request.Name;

            await _roleManager.UpdateAsync(role);

            TempData["RoleUpdated"] = true;

            return View();
        }


        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ModelState.AddModelError(string.Empty, "Böyle bir rol bulunamadı.");
                TempData["RoleNotDeleted"] = true;
                return RedirectToAction(nameof(RoleController.RoleList));
            }

            var result = await _roleManager.DeleteAsync(role);

            if (!result.Succeeded)
            {
                ModelState.AddModelErrorList(result.Errors);
                TempData["RoleNotDeleted"] = true;
                return RedirectToAction(nameof(RoleController.RoleList));
            }

            TempData["RoleDeleted"] = true;
            return RedirectToAction(nameof(RoleController.RoleList));
        }

        public async Task<IActionResult> AssignRoleToUser(string userId)
        {
            var user = (await _userManager.FindByIdAsync(userId))!;

            ViewBag.userId = userId;

            var roles = await _roleManager.Roles.ToListAsync();

            var userRoles = await _userManager.GetRolesAsync(user);

            var roleViewModelList = new List<AssignRoleToUserViewModel>();



            var userGeneralVM = new UserGeneralViewModel
            {
                Email = user.Email,
                FullName = user.FullName,
                Username = user.UserName,
                UserPicture = user.Picture
            };


            foreach (var role in roles)
            {
                var assignRoleToUserVM = new AssignRoleToUserViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name,
                };

                if (userRoles.Contains(role.Name))
                {
                    assignRoleToUserVM.IsExist = true;
                }

                roleViewModelList.Add(assignRoleToUserVM);
            }

            var userRoleInfoVM = new UserRoleInfoViewModel
            {
                AssignRoleToUserViewModel = roleViewModelList,
                UserGeneralViewModel = userGeneralVM,
            };

            return View(userRoleInfoVM);
        }


        [HttpPost]
        public async Task<IActionResult> AssignRoleToUser(string userId, UserRoleInfoViewModel requestList)
        {
            var user = (await _userManager.FindByIdAsync(userId))!;

            foreach (var role in requestList.AssignRoleToUserViewModel)
            {
                if (role.IsExist)
                {
                    await _userManager.AddToRoleAsync(user, role.RoleName);
                }
                else
                {
                    await _userManager.RemoveFromRoleAsync(user, role.RoleName);
                }
            }

            TempData["RoleAssigned"] = true;

            return RedirectToAction(nameof(DashboardController.UserList), "Dashboard");
        }
    }
}

Web/Areas/Admin/Views/Role/AssignRoleToUser.cshtml
@model UserRoleInfoViewModel


@{
    ViewData["Title"] = "Rol Ata";
}

<h1>Rol Ata</h1>

<div class="row">
    <div class="col-md-6">




        <div asp-validation-summary=ModelOnly class="ui negative message w-75">
            <i class="close icon"></i>
            <div class="header">
                HATA
            </div>
            <p></p>
        </div>

        <form class="mt-4" asp-route-userId="@ViewBag.userId" asp-area="Admin" asp-controller="Role" asp-action="AssignRoleToUser" method="post">

            <div class="row">
                @for (int i = 0; i < Model.AssignRoleToUserViewModel.Count; i++)
                {
                    <div class="ui slider checkbox mb-5 col-md-4">
                        <input type="checkbox" asp-for="@Model.AssignRoleToUserViewModel[i].IsExist">
                        @*  <input type="checkbox" class="form-check-input" asp-for="@Model.AssignRoleToUserViewModel[i].IsExist"> *@
                        <label>@Model.AssignRoleToUserViewModel[i].RoleName</label>
                        <input type="hidden" asp-for="@Model.AssignRoleToUserViewModel[i].RoleName" />
                        <input type="hidden" asp-for="@Model.AssignRoleToUserViewModel[i].RoleId" />
                    </div>
                }
            </div>

            <div class="mt-5">
                <a class="ui black button me-4" onclick="history.back()"><i class="bi bi-arrow-left-circle me-2"></i>Geri dön</a>
                <button class="ui blue button ms-4" type="submit">Rolü ata</button>
            </div>
        </form>
    </div>

    <div class="col-md-6">

        <div class="ui card">
            <div class="image">
                @if (@Model.UserGeneralViewModel.UserPicture != null)
                {
                    <img src="~/uploads/userPictures/@Model.UserGeneralViewModel.UserPicture">

                }
                else
                {
                    <img src="~/uploads/userPictures/defaultUserPhoto.jpg">
                }
            </div>
            <div class="content text-center">
                <p class="header">@Model.UserGeneralViewModel.FullName</p>
                <div class="meta">
                    <p>@Model.UserGeneralViewModel.Username</p>
                </div>
                <div class="description">
                    @Model.UserGeneralViewModel.Email
                </div>
            </div>
            <div class="extra content">
                <p class="text-dark text-center">
                    <strong class="text-danger">*</strong>Bu kullanıcı için rol ataması yapıyorsunuz.
                </p>
            </div>
        </div>

    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Web/Areas/Admin/Views/Role/CreateRole.cshtml
@model CreateRoleViewModel

@{
    ViewData["Title"] = "Rol Oluştur";
}

<h1>Rol Oluştur</h1>


<div class="row">
    <div class="col-md-6">

        @if (TempData["RoleAdded"] as bool? ?? false)
        {
            <div class="ui success message">
                <i class="close icon"></i>
                <div class="mt-2">
                    <p>Rol başarıyla eklendi.</p>
                </div>
            </div>
        }
        <div asp-validation-summary=ModelOnly class="ui negative message w-75">
            <i class="close icon"></i>
            <div class="header">
                HATA
            </div>
            <p></p>
        </div>

        <form asp-action="CreateRole" method="post">

            <div class="ui form">
                <div class="two fields ">

                    <div class="field">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" type="text" wfd-id="id57" required>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
            </div>


            <div class="mt-4">
                <button class="ui blue button" type="submit">Oluştur</button>
                <a class="ui black button ms-4" asp-area="Admin" asp-controller="Role" asp-action="RoleList">Rollere git</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Web/Areas/Admin/Views/Role/RoleList.cshtml
@model List<RoleListViewModel>

@{
    ViewData["Title"] = "RoleList";
}

<div class="text-center d-flex justify-content-between mt-4">
    <h1 class="fw-light">RoleList</h1>


    @if (TempData["RoleDeleted"] as bool? ?? false)
    {
        <div class="ui warning message">
            <i class="close icon"></i>
            <div class="mt-2 mx-3">
                <p>Rol silindi.</p>
            </div>
        </div>
    }

    @if (TempData["RoleNotDeleted"] as bool? ?? false)
    {
        <div class="ui negative message">
            <i class="close icon"></i>
            <div class="mt-2 mx-3">
                <p>Rol silinemedi!</p>
            </div>
        </div>
    }



    <a asp-action="CreateRole">
        <button class="ui blue button fw-bold">Rol ekle</button>
    </a>
</div>

<div class="container mt-4">
    <table class="ui red table selectable">
        <thead>
        <tr>
            <th>Id</th>
            <th>RoleName</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>
                    <a class="btn btn-warning text-dark me-4" asp-area="Admin" asp-controller="Role" asp-action="UpdateRole" asp-route-id="@item.Id">Güncelle</a>
                    <a class="btn btn-danger" asp-area="Admin" asp-controller="Role" asp-action="DeleteRole" asp-route-id="@item.Id">Sil</a>
                </td>
            </tr>
        }

        </tbody>
    </table>

</div>

Web/Areas/Admin/Views/Role/UpdateRole.cshtml
@model UpdateRoleViewModel

@{
    ViewData["Title"] = "Rol Güncelle";
}

<h1>Rol Güncelle</h1>


<div class="row">
    <div class="col-md-6">

        @if (TempData["RoleUpdated"] as bool? ?? false)
        {
            <div class="ui success message">
                <i class="close icon"></i>
                <div class="mt-2">
                    <p>Rol başarıyla güncellendi.</p>
                </div>
            </div>
        }
        <div asp-validation-summary=ModelOnly class="ui negative message w-75">
            <i class="close icon"></i>
            <div class="header">
                HATA
            </div>
            <p></p>
        </div>

        <form asp-action="UpdateRole" method="post">
            
            <input type="hidden" asp-for="Id"/>

            <div class="ui form">
                <div class="two fields ">

                    <div class="field">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" type="text" wfd-id="id57" required>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
            </div>


            <div class="mt-4">
                <button class="ui blue button" type="submit">Güncelle</button>
                <a class="ui black button ms-4" asp-area="Admin" asp-controller="Role" asp-action="RoleList">Rollere git</a>
            </div>
        </form>

       
        
      
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}